### PR TITLE
Fix JSON-RPC v2 errors

### LINKED ISSUE #102: JSON-RPC errors are sent as string instead of object, not following JSON-RPC spec
This issue is essentially a duplicate of https://github.com/romanz/electrs/issues/313, which was fixed in https://github.com/romanz/electrs/pull/390, https://github.com/romanz/electrs/pull/398 and https://github.com/romanz/electrs/pull/421 (as far as I can see - branching makes it a bit confusing).

Errors are returned as a string instead of an object. Here is an example of a batched response error:
```
[{"error":"verbose transactions are currently unsupported","id":204,"jsonrpc":"2.0"}]
```

which should be returned as 
```
[{"error":{"code":-32601,"message":"verbose transactions are currently unsupported"},"id":204,"jsonrpc":"2.0"}]
```

following the [JSON-RPC 2.0 spec](https://www.jsonrpc.org/specification#error_object).

Unfortunately this is a blocker for upgrading to batched JSON-RPC support on Sparrow currently.

### PR DESCRIPTION
**Pull request by junderw**
Fixes #102

### CODE REVIEW

File: src/electrum/server.rs [hunk 1]
```diff
@@ -461,7 +483,7 @@ impl Connection {
                     params,
                     e.display_chain()
                 );
-                json!({"jsonrpc": "2.0", "id": id, "error": format!("{}", e)})
```
Comment (junderw) [inline src/electrum/server.rs:464]: This was the main problem area from the connected issue.

**Comment by wiz** [comment]
request review by @mononaut

**Review by mononaut — APPROVED** [review]
Tested ACK @ [277b05b7]

JSON-RPC errors are now returned in the proper format, and valid JSON-RPC requests still work ok.
