### PR TITLE
REST: Return an f64 for difficulty from the block value endpoint

### LINKED ISSUE #3: block difficulty value is integer instead of floating point
Moved from https://github.com/Blockstream/esplora/issues/370

### How to Reproduce
https://blockstream.info/api/block/000000006e082edaab177e74a7cc0db2a6b908812ae801d535e0f2033aa8657d

### Expected Value
  "difficulty": 1.182899534312841,

## Actual Value
"difficulty":1

### PR DESCRIPTION
**Pull request by junderw**
Closes #3 

---

### Affects API interface AND/OR response data format? == **Changes difficulty from integer to float... though, from a JSON perspective that isn't really "change" per se**

---

This doesn't require bumping rust-bitcoin dep.

This method was based on the method I used here: https://github.com/rust-bitcoin/rust-bitcoin/pull/1707

In the blog post here: https://blog.m-ou.se/floats/

### CODE REVIEW

File: src/rest.rs [hunk 1]
```diff
@@ -104,14 +104,62 @@ impl BlockValue {
...
+// Current version of rust-bitcoin ignores the Network and always returned
+// the max target of bitcoin mainnet. Therefore the Network is irrelevant.
+const TARGET_MAX_F64: f64 = 2.695953529101131e67;
+
+fn difficulty_new(bh: &bitcoin::BlockHeader) -> f64 {
+    TARGET_MAX_F64 / u256_to_f64(bh.target())
+}
+
+#[inline]
+fn u256_to_f64(input: bitcoin::util::uint::Uint256) -> f64 {
```
Comment (Kixunil) [inline src/rest.rs]: FYI this type will be hidden in the next release (soon), so after bumping the version this whole code has to be deleted. I suggest you just wait for the release (unless this is urgent and you can't spend time resolving *other* breakages).

**Comment by wiz** [comment]
@mononaut it would be nice if we can remove all the ugly hacks we added to get the difficulty from core instead of electrs for 3.0, wdyt?

**Review by softsimon — CHANGES_REQUESTED** [review]
There seem to be a difference in the rounding between Core and this.

Example 1: 000000000003ba27aa200b1cecaad478d2b00432346c3f1f3986da1afd33e506

14484.1623612254 (Core)
14484.162361225399 (Electrs with this PR)

Example 2: 000000000000034a7dedef4a161fa058a2d67a173a90155f3a2fe6fc132e0ebf
2864140.507810974 (core)
2864140.5078109736 (electrs)

**Comment by junderw** [comment]
> There seem to be a difference in the rounding between Core and this.

I think this is acceptable.

In Element chat we have proven that even a 1:1 re-implementation of the Bitcoin Core logic results in differing precision.

This is likely due to the differences in the integer to float coercion in C++ vs. Rust.

Rust is more precise. C++ is less precise.

That said, it seems like different versions of Bitcoin Core (like the old ones that use older versions of C++) have differing precisions for the floats (due to C++ implementation of integer to float conversion changing).

If we want to always be === exactly to Bitcoin Core, there's no getting around asking Bitcoin Core directly for it.

**Comment by junderw** [comment]
That said. If we want to use the 1:1 re-implementation (since I made it anyways) that would be fine. (the results would be the same, slightly more precise floats, but at least we can say "ported from Bitcoin Core" heh)

The re-implementation from core only uses u32 and f64, so implementing float conversion for U256 would no longer be necessary.

**Comment by junderw** [comment]
https://github.com/serde-rs/json/issues/1041

@softsimon I found a way to make the difficulty match Bitcoin Core exactly, but the workaround will be very VERY ugly and hard to review. lol (Edit: this turned out to not be correct for some difficulties. There seems to be some other extra logic in the C++ compiler causing slight variations in sig fig count.)

I also extracted the values from Bitcoin Core for every difficulty period since the difficulty changed from 1.0... so I can add those as test cases to make sure we match exactly for every difficulty so far.

**Comment by junderw** [comment]
Just in case anyone ever has need for all the difficulties on the blockchain, here's a script I wrote:

```bash
OUTPUT="const VECTORS: &[(&str, &str, u32, &str)] = &["

for i in $(seq 30240 2016 796320); do
	BHASH=$(bitcoin-cli getblockstats $i '["blockhash"]' | grep blockhash | cut -d\" -f4)
        HEADER="$(bitcoin-cli getblockheader $BHASH)"

	OUTPUT="$OUTPUT
    (
        \"Block height $i\",
        $(echo "$HEADER" | grep '"hash' | cut -d' ' -f4)
        0x$(echo "$HEADER" | grep 'bits' | cut -d\" -f4),
        \"$(echo "$HEADER" | grep 'difficulty' | cut -d' ' -f4 | cut -d',' -f1)\",
    ),"

done;

OUTPUT="$OUTPUT
];"

echo "$OUTPUT" > output.txt
```

<details>
 <summary>Click here for the output currently</summary>

```rust
const VECTORS: &[(&str, &str, u32, &str)] = &[
    (
        "Block height 30240",
        "000000000fa8bfa0f0dd32f956b874b2c7f1772c5fbedcb1b35e03335c7fb0a8",
        0x1d00ffff,
        "1",
    ),
    (
        "Block height 32256",
        "000000004f2886a170adb7204cb0c7a824217dd24d11a74423d564c4e0904967",
        0x1d00d86a,
        "1.182899534312841",
    ),
    (
        "Block height 34272",
        "000000002732d387256b57cabdcb17767e3d30e220ea73f844b1907c0b5919ea",
        0x1d00c428,
        "1.305062131591525",
    ),
    (
        "Block height 36288",
        "0000000040514b192e6ca247d83388bf11cb1d5e980610ae2c6324cbb0594b32",
        0x1d00be71,
        "1.344224970771029",
    ),
    (
        "Block height 38304",
        "0000000015bb50096055846954f7120e30d6aa2bd5ab8d4a4055ceacc853328a",
        0x1d008cc3,
        "1.818648536145414",
    ),
    (
        "Block height 40320",
        "0000000045861e169b5a961b7034f8de9e98022e7a39100dde3ae3ea240d7245",
        0x1c654657,
        "2.527738215072359",
    ),
    (
        "Block height 42336",
        "000000000b0078371753a9813d3f902008cec296451cf5d721e4660a2fba9612",
        0x1c43b3e5,
        "3.781179252033766",
    ),
    (
        "Block height 44352",
        "0000000026cdac72c9b2eb5ac20d987f7cb30118203528245a34ba1dc0f0d7a3",
        0x1c387f6f,
        "4.531081750070693",
    ),
    (
        "Block height 46368",
        "0000000027c99f9712286d6f3bd01f4d6de7b8bcce586c92f7a131b96d5d96c6",
        0x1c381375,
        "4.56516291033707",
    ),
    (
        "Block height 48384",
        "000000000f8bad9641203f9d788e72d55ff164f1a62a3e230df6f411f7d7d8fc",
        0x1c2a1115,
        "6.085476906000794",
    ),
    (
        "Block height 50400",
        "000000001af6e66db5628c7ba98501623bd23ea6d720571ffedf007973be07c9",
        0x1c20bca7,
        "7.819796993353832",
    ),
    (
        "Block height 52416",
        "00000000079f22d04081de2b3961e7bb1037051df3d178a4bc3258dae9a3ab63",
        0x1c16546f,
        "11.46431580551412",
    ),
    (
        "Block height 54432",
        "00000000021df73bddc56ff2bae4637099c096a1eba98ae631623d21b58877d6",
        0x1c13ec53,
        "12.84918314782378",
    ),
    (
        "Block height 56448",
        "00000000051a16879d044e2f58b60ecaedc9dc92a00416f9035ccc018e72f4ed",
        0x1c159c24,
        "11.84622814970471",
    ),
    (
        "Block height 58464",
        "0000000008c7b770615ca86782c41b97630c8fa23de40cabf3a2722224f9b799",
        0x1c0f675c,
        "16.61907875185736",
    ),
    (
        "Block height 60480",
        "000000000632e22ce73ed38f46d5b408ff1cff2cc9e10daaf437dfd655153837",
        0x1c0eba64,
        "17.38148815814011",
    ),
    (
        "Block height 62496",
        "00000000025825d92ecf024c9055af90f2fe92f5796aaffc61a3d95574bb3b76",
        0x1c0d3142,
        "19.40479632838217",
    ),
    (
        "Block height 64512",
        "000000000a20ed505ca567ec4611616790a1e3c49bc9bdd82ff6bd773e32db2a",
        0x1c0ae493,
        "23.50125722290317",
    ),
    (
        "Block height 66528",
        "0000000002216521d1a33de5bf19b3f8966395fbc81be449e2b2f1bdab2bd88f",
        0x1c05a3f4,
        "45.38582234101263",
    ),
    (
        "Block height 68544",
        "0000000000519051eb5f3c5943cdbc176a0eff4e1fbc3e08287bdb76299b8e5c",
        0x1c0168fd,
        "181.5432893640505",
    ),
    (
        "Block height 70560",
        "0000000000c4f919e27398ec17fe39ca0e8936596e7eeeb21f06d87e851df90e",
        0x1c010c5a,
        "244.2132230923753",
    ),
    (
        "Block height 72576",
        "00000000002897d721b6b31ad519e3e54a90741a24a019f23e41911a8c8b0d25",
        0x1c00ba18,
        "352.1612090680101",
    ),
    (
        "Block height 74592",
        "0000000000365da40798b3cea463f8307ff8b7bf828254721a7d4d270a35ee62",
        0x1c00800e,
        "511.7735342566043",
    ),
    (
        "Block height 76608",
        "00000000002d3c0657d352f28051fbfffda76ce99ddf5256dddebf4c9ee6cad4",
        0x1b692098,
        "623.3869598689275",
    ),
    (
        "Block height 78624",
        "00000000005174bca5fb1486b0cf216e2841560cd28db35839658a3583709983",
        0x1b5bede6,
        "712.8848645520973",
    ),
    (
        "Block height 80640",
        "0000000000307c80b87edf9f6a0697e2f01db67e518c8a4d6065d1d859a3a659",
        0x1b4766ed,
        "917.8307413015116",
    ),
    (
        "Block height 82656",
        "000000000024fc69f5415908b1960092a8e81b9d3b9a03c1133f5cb0a2d3c2af",
        0x1b31b2a3,
        "1318.670050153592",
    ),
    (
        "Block height 84672",
        "000000000006bee26b7ce695f7324381b48361ddde16c6922867e665a0df8430",
        0x1b2f8e9d,
        "1378.028165037326",
    ),
    (
        "Block height 86688",
        "000000000015bfe777e893c4ebd1307541792630c2932278bfe8cf3ae82668ce",
        0x1b1e7eca,
        "2149.021814946726",
    ),
    (
        "Block height 88704",
        "000000000012384edfbd167c7778aec3e84bb1795b907cc795912e643c2cff04",
        0x1b153263,
        "3091.736890411797",
    ),
    (
        "Block height 90720",
        "0000000000042751f341ee2dde050240cd8330401063dfdea21be270495bf360",
        0x1b0e7256,
        "4536.353723275037",
    ),
    (
        "Block height 92736",
        "00000000000615837a43bdec942b048bd28d48aba5d73b0c79617ccc71d56e68",
        0x1b098b2a,
        "6866.898648972739",
    ),
    (
        "Block height 94752",
        "00000000000612274477875b7ceb71488c060f9f718435122e0369a720c5f78f",
        0x1b081cd2,
        "8078.195257925088",
    ),
    (
        "Block height 96768",
        "00000000000481ef73efe6cb2ad1e9c1e3d1c46e712f6aeb6d5079b539d12246",
        0x1b055953,
        "12251.9997603745",
    ),
    (
        "Block height 98784",
        "0000000000043c4b0ed186109c36ce09e9af29b8ed0fdebcb909fa338877743d",
        0x1b04864c,
        "14484.1623612254",
    ),
    (
        "Block height 100800",
        "000000000000e383d43cc471c64a9a4a46794026989ef4ff9611d5acb704e47a",
        0x1b0404cb,
        "16307.42093852398",
    ),
    (
        "Block height 102816",
        "0000000000036e1b1c66c51814ee2f500f3e67d8e568f5606b91ad3359e68c0d",
        0x1b038dee,
        "18437.64439216629",
    ),
    (
        "Block height 104832",
        "0000000000018cfcff9528bdb69f53cce09e9705ed2681bb68f441b27b64cfa4",
        0x1b02fa29,
        "22012.38133799388",
    ),
    (
        "Block height 106848",
        "000000000000be2bc4445d0c929adaa79e6106528b8cc8651f1a0bba37bc0c1b",
        0x1b028552,
        "25997.87992881442",
    ),
    (
        "Block height 108864",
        "00000000000199206616e77986c26e500819a323feb51799b57c6fa6fbbe9850",
        0x1b01cc26,
        "36459.88692507513",
    ),
    (
        "Block height 110880",
        "0000000000004169640bb33c01f4417aefda88a1fabfa4f06f331d823df95fa2",
        0x1b012dcd,
        "55589.51812686866",
    ),
    (
        "Block height 112896",
        "000000000000cb6aeb7e251ed31a814d9631b5fe3d6994e00229f7ebbfae5344",
        0x1b00dc31,
        "76192.61934751371",
    ),
    (
        "Block height 114912",
        "000000000000a8c2cc7f45568c20d3498eba889a182dd72db10d7e7a98fb9f97",
        0x1b00f339,
        "68977.78463020959",
    ),
    (
        "Block height 116928",
        "000000000000494457221111a6a99da34a993c69c2761582bec31f90ba5d560d",
        0x1b00cbbd,
        "82345.64411296662",
    ),
    (
        "Block height 118944",
        "0000000000006995e63e3533e1cc04d0d276fca4cab6241387e6e385da004c88",
        0x1b00b5ac,
        "92347.59095209427",
    ),
    (
        "Block height 120960",
        "0000000000002c920cf7e4406b969ae9c807b5c4f271f490ca3de1b0770836fc",
        0x1b0098fa,
        "109670.1332924774",
    ),
    (
        "Block height 122976",
        "0000000000003b10472364bf9183984bce1c54e6445ee997f193cbea40e65336",
        0x1a6a93b3,
        "157416.4018436489",
    ),
    (
        "Block height 124992",
        "0000000000000f79d738bed3e162d5c6426d3750baedd35474fe2fa6644fc5dc",
        0x1a44b9f2,
        "244112.4877743364",
    ),
    (
        "Block height 127008",
        "000000000000044522dc766048c29411bcfe6134a1ae4a017c4b8623d7f3628d",
        0x1a269421,
        "434877.0455276276",
    ),
    (
        "Block height 129024",
        "0000000000000f65a12b5ef560a95d7da6cc512e908bc7af3b7a1b0c02673a7f",
        0x1a1d932f,
        "567269.530162422",
    ),
    (
        "Block height 131040",
        "000000000000097aa651b8e19c448924586a8010721c8e7ea282a0272d425987",
        0x1a132185,
        "876954.4935135372",
    ),
    (
        "Block height 133056",
        "000000000000047846f0776c901542540d555b9861cee16e9788611a3aef333a",
        0x1a0c2a12,
        "1379192.288228078",
    ),
    (
        "Block height 135072",
        "00000000000006f5d58e11e705c01b33a87f6d31f6b5bded34f01c68ad4e3d61",
        0x1a0abbcf,
        "1563027.996116223",
    ),
    (
        "Block height 137088",
        "00000000000004a16fcd74d18ddce2bddd6f0177b7a6dcde6feaf1be8d21ed60",
        0x1a09ec04,
        "1690895.803052393",
    ),
    (
        "Block height 139104",
        "00000000000003f62ca68937e18496121ccd2858b2b43099525d3f92015b0afd",
        0x1a08e1e5,
        "1888786.705353048",
    ),
    (
        "Block height 141120",
        "00000000000002d214e1af085eda0a780a8446698ab5c0128b6392e189886114",
        0x1a094a86,
        "1805700.836193673",
    ),
    (
        "Block height 143136",
        "000000000000082e8dea125fbd7c2cb326a90f9bda166e9b8366034447e67e86",
        0x1a096fe3,
        "1777774.482001465",
    ),
    (
        "Block height 145152",
        "0000000000000801bdcb94693c976e697eb428f64808bebdaa733a98e2bbdc1b",
        0x1a098ea5,
        "1755425.320328703",
    ),
    (
        "Block height 147168",
        "00000000000001bb39ec9d373044cfecb999f11316853cdff6ebc6deafcc736d",
        0x1a09ee5d,
        "1689334.404597101",
    ),
    (
        "Block height 149184",
        "000000000000028c550f87b05cddb1f4d461451bb26f0706f1ed5b20e3889fb9",
        0x1a0b6d4b,
        "1468195.427220831",
    ),
    (
        "Block height 151200",
        "0000000000000b9746bae9c3dae632c01ecb831fc0a46097cb5575be4f895885",
        0x1a0df0ca,
        "1203461.926379965",
    ),
    (
        "Block height 153216",
        "00000000000003f1a73e5afdbe072366db61a6937f5d42fac0a855871d09be24",
        0x1a0e119a,
        "1192497.750089478",
    ),
    (
        "Block height 155232",
        "000000000000030b4517cb265ce52030512bc28199de2443c53492861453f574",
        0x1a0f61b1,
        "1090715.680051267",
    ),
    (
        "Block height 157248",
        "0000000000000cc4a5039ae51d1733506684142f7f44855e1e4c9c7385faf2f3",
        0x1a0e8668,
        "1155038.333963644",
    ),
    (
        "Block height 159264",
        "0000000000000aeb0e2e314dcbf78baea4cd3aacf4d559cbff6b6598b5f1373a",
        0x1a0e76ba,
        "1159929.497224385",
    ),
    (
        "Block height 161280",
        "00000000000005911fe26209de7ff510a8306475b75ceffd434b68dc31943b99",
        0x1a0d69d7,
        "1250757.739274659",
    ),
    (
        "Block height 163296",
        "00000000000000d5ec6ec7c1f16122f714b05e9142b404ed2519794925e9f20c",
        0x1a0cd43f,
        "1307728.360604068",
    ),
    (
        "Block height 165312",
        "0000000000000311a46b264090bd3a11a5855ca4a5d889329fcb5963ea4d677e",
        0x1a0c290b,
        "1379647.439214294",
    ),
    (
        "Block height 167328",
        "0000000000000034781c434d8cc9d1bfaf6ba003846ca7e37317a207e1d5d7c9",
        0x1a0c309c,
        "1376302.26788638",
    ),
    (
        "Block height 169344",
        "00000000000002bbb1abb31a56eed021c62da8082d38805541123a19e1292f20",
        0x1a0b350c,
        "1496978.595025569",
    ),
    (
        "Block height 171360",
        "0000000000000566827ced9a659e0e292a50c21397a90539e718aa49ce071f5c",
        0x1a0b3287,
        "1498294.362816507",
    ),
    (
        "Block height 173376",
        "0000000000000852ab1f02c0e1794d9e9a88aa5db0be7bf63be1e6cb9d815539",
        0x1a0a507e,
        "1626553.481328943",
    ),
    (
        "Block height 175392",
        "000000000000034faff2c6f8d019238fd7813c123c072cfddd59207ace6edd35",
        0x1a0aa1e3,
        "1577913.485676726",
    ),
    (
        "Block height 177408",
        "0000000000000098ae5ccac3262536542b2f85f181d3ac5967ba9449c2bb9939",
        0x1a0b1ef7,
        "1508589.672060295",
    ),
    (
        "Block height 179424",
        "0000000000000780e8d7d382e048c522bd4882664addfd5e66c27d6d1377b83f",
        0x1a09ae02,
        "1733207.513848385",
    ),
    (
        "Block height 181440",
        "00000000000000e527fc19df0992d58c12b98ef5a17544696bbba67812ef0e64",
        0x1a0a8b5f,
        "1591074.961847305",
    ),
    (
        "Block height 183456",
        "00000000000001785088bf24f2045574242a40b2d701a1381fb7c329edcf4c9f",
        0x1a0a98d6,
        "1583177.847444009",
    ),
    (
        "Block height 185472",
        "00000000000005315a6b6d9d83534cd0438e7c2cc28c610f05410ba754af05bb",
        0x1a09b78a,
        "1726566.55919348",
    ),
    (
        "Block height 187488",
        "00000000000008deb39e2eeee2f06eae8c3b453823aaae27460394c9cd7ca3f5",
        0x1a099431,
        "1751454.535340679",
    ),
    (
        "Block height 189504",
        "00000000000003de835c2a316443333d9fb1eb08ca22868f79b7960aef6512fd",
        0x1a08fd2e,
        "1866391.305003208",
    ),
    (
        "Block height 191520",
        "00000000000004364825b6280a94eed1104308e5bb6d72a6e322aa28b71bcf78",
        0x1a083cc9,
        "2036671.08869332",
    ),
    (
        "Block height 193536",
        "00000000000001ec364644aa29dd604ad833b08ead382ed09ec12427c1f26086",
        0x1a07a85e,
        "2190865.970102859",
    ),
    (
        "Block height 195552",
        "000000000000066ad90c11aba4a96c5c9fbda6e1021882a6661b85d860f3d627",
        0x1a06dfbe,
        "2440642.606915963",
    ),
    (
        "Block height 197568",
        "00000000000003f64d7662362aba91a5bdccbdbf6574fb42ddca28f1f0ec11fe",
        0x1a063a38,
        "2694047.952955013",
    ),
    (
        "Block height 199584",
        "000000000000002e00a243fe9aa49c78f573091d17372c2ae0ae5e0f24f55b52",
        0x1a05db8b,
        "2864140.507810974",
    ),
    (
        "Block height 201600",
        "00000000000003a5e28bef30ad31f1f9be706e91ae9dda54179a95c9f9cd9ad0",
        0x1a057e08,
        "3054627.526948636",
    ),
    (
        "Block height 203616",
        "00000000000003010530e33a849b27ded874202911e9e63263cb49245744fb9e",
        0x1a0575ef,
        "3072321.732020756",
    ),
    (
        "Block height 205632",
        "000000000000020b503f6dbeda2769247f129e24e9d4f9092ce838db45d13f30",
        0x1a0513c5,
        "3304356.392990344",
    ),
    (
        "Block height 207648",
        "000000000000037c464073f6f83977cc6d989125f4dfe92fea67a853c2494e40",
        0x1a04faeb,
        "3368767.140532939",
    ),
    (
        "Block height 209664",
        "00000000000001643623e3cf2456a2983c1915228a17f651a30c2eda4e300eda",
        0x1a04e0ea,
        "3438908.960159138",
    ),
    (
        "Block height 211680",
        "0000000000000411474b575b792c9cbaf01eecfb6b33ff03766d51fc4133b668",
        0x1a04fa62,
        "3370181.799277837",
    ),
    (
        "Block height 213696",
        "000000000000036d393cc83cc00fbe1de555341aa1b8691b902ce30c8f568cd0",
        0x1a05a16b,
        "2979636.616938074",
    ),
    (
        "Block height 215712",
        "00000000000004d5e7a5977e1f7817b5fcee90d8ab0dbf9d976375a1b8639c95",
        0x1a0529b1,
        "3249549.584487207",
    ),
    (
        "Block height 217728",
        "00000000000004d2b999b30a6716e366809b5416ab8834b0ae390765d75efbb5",
        0x1a05a6b1,
        "2968775.332075074",
    ),
    (
        "Block height 219744",
        "0000000000000470b20d91d56cc90710fa79af2eced21b39206a05a4e20f9838",
        0x1a051f3c,
        "3275464.586565617",
    ),
    (
        "Block height 221760",
        "00000000000000fc85dd77ea5ed6020f9e333589392560b40908d3264bd1f401",
        0x1a04985c,
        "3651011.630693214",
    ),
    (
        "Block height 223776",
        "0000000000000128b2967ba59e32792733a87b3c7f2a3045d50a52f2c3d978f9",
        0x1a03d74b,
        "4367876.000842196",
    ),
    (
        "Block height 225792",
        "0000000000000024b134023619ea04aa80d572b9bafe09383b91db31c13ca4d2",
        0x1a0375fa,
        "4847647.152065606",
    ),
    (
        "Block height 227808",
        "000000000000023003f076a58d63092ff453e30611e214dcb0b9e8f94bf52433",
        0x1a02816e,
        "6695826.282596251",
    ),
    (
        "Block height 229824",
        "0000000000000041e4dbc0056e1a0556885fb76cc4467a29fc70a20cb8138b33",
        0x1a022fbe,
        "7672999.920164138",
    ),
    (
        "Block height 231840",
        "00000000000000a93b6a1604ad96455f1058c7e411681d8885adcd1819db9543",
        0x1a01de94,
        "8974296.014887851",
    ),
    (
        "Block height 233856",
        "000000000000006b9106b7f0bf5fdff6949d67b0b41705cf2cc146265c3f6103",
        0x1a01aa3d,
        "10076292.88341872",
    ),
    (
        "Block height 235872",
        "000000000000010b6e3e43c6189856f3c21059301fdffaa704336db3c981a035",
        0x1a017fe9,
        "11187257.46136079",
    ),
    (
        "Block height 237888",
        "0000000000000015838b499ceb6905e27a45ceb871d6817914c81f81dfed23e2",
        0x1a016164,
        "12153411.70977583",
    ),
    (
        "Block height 239904",
        "00000000000000f8c20a9d01ea73cae3d33ae59362244d0664b907463fa929c5",
        0x1a011337,
        "15605632.68128593",
    ),
    (
        "Block height 241920",
        "00000000000000b79f259ad14635739aaf0cc48875874b6aeecc7308267b50fa",
        0x1a00de15,
        "19339258.27238668",
    ),
    (
        "Block height 243936",
        "0000000000000085cd2f41fb708131fb0a373a0456b7296470c0d80c3ff7381b",
        0x1a00c94e,
        "21335329.113983",
    ),
    (
        "Block height 245952",
        "000000000000005b821d40c0541a641f7bbc5e4c1ef7cf046371c1ad2191d3c1",
        0x1a00a429,
        "26162875.6825699",
    ),
    (
        "Block height 247968",
        "000000000000008664d94cadffaa48ae959579a0f7d5eb1b1593481a2015981f",
        0x1a008968,
        "31256960.72776893",
    ),
    (
        "Block height 249984",
        "000000000000006f68295a01c059e45c38fe3ff5095107f067c52ae6437c3d4b",
        0x1972dbf2,
        "37392766.13647456",
    ),
    (
        "Block height 252000",
        "00000000000000200e99940b296ded4ce16462bba1950453b29abf313ba7cc47",
        0x19548732,
        "50810339.04827648",
    ),
    (
        "Block height 254016",
        "0000000000000035ddc04df84d4ceb10446d447b482462f0303690bf5390ae17",
        0x19415257,
        "65750060.14908481",
    ),
    (
        "Block height 256032",
        "000000000000001a7551c8d0d76d1095287a7fbae6a8aa8976d12d51b540147a",
        0x1931679c,
        "86933017.77119441",
    ),
    (
        "Block height 258048",
        "000000000000000e2125022ec060f975d945fa7f42dd63b95ec8dc96b6e2a8a2",
        0x19262222,
        "112628548.6663471",
    ),
    (
        "Block height 260064",
        "000000000000000bc10c6a3a18f82a3991553008ba1114b6e4759d47328b215f",
        0x191cdc20,
        "148819199.8050926",
    ),
    (
        "Block height 262080",
        "000000000000000aa77be1c33deac6b8d3b7b0757d02ce72fffddc768235d0e2",
        0x1916b0ca,
        "189281249.2810329",
    ),
    (
        "Block height 264096",
        "000000000000000c6b03a623548f813cf4981b53f7f0fb5d483024d8b7448c8d",
        0x19100ab6,
        "267731249.4824211",
    ),
    (
        "Block height 266112",
        "0000000000000002dcb82740d4331da4dd46b872e4febf98e636bae40b69d83c",
        0x190afc85,
        "390928787.6380858",
    ),
    (
        "Block height 268128",
        "00000000000000079c3020a8304ec736e97b570f52aca00f836d02d5a9a4c26b",
        0x190867f3,
        "510929738.0161518",
    ),
    (
        "Block height 270144",
        "0000000000000004da994162f083e9744f1c93e8b9035554bbbd784d59465f72",
        0x19070bfb,
        "609482679.8883545",
    ),
    (
        "Block height 272160",
        "00000000000000028465cbaff46f250aad462c42ea663c7084f8e311e3db8301",
        0x19061242,
        "707408283.0514966",
    ),
    (
        "Block height 274176",
        "0000000000000003cbb18a8ea04e14452ad0c3bc92ed709e4df5a50b2a24da0e",
        0x1904ba6e,
        "908350862.437022",
    ),
    (
        "Block height 276192",
        "000000000000000390e14991429d55d122f0110fd3fdf2927432ca825c498d81",
        0x1903a30c,
        "1180923195.258026",
    ),
    (
        "Block height 278208",
        "00000000000000025342f9c0e2bbba993220562f05d9b1532cd88a40e07af74e",
        0x1903071f,
        "1418481395.262635",
    ),
    (
        "Block height 280224",
        "00000000000000000b5d59a15f831e1c45cb688a4db6b0a60054d49a9997fa34",
        0x19026666,
        "1789546951.053241",
    ),
    (
        "Block height 282240",
        "0000000000000000ef9ee7529607286669763763e0c46acfdefd8a2306de5ca8",
        0x1901f52c,
        "2193847870.174279",
    ),
    (
        "Block height 284256",
        "0000000000000001541d6853bfdfc9ec2ce46499c8469b338ade9818715fe1a0",
        0x1901a36e,
        "2621404453.064615",
    ),
    (
        "Block height 286272",
        "00000000000000005e694903146a75eff30f43068a71288cd76289a9efe8dc07",
        0x19015f53,
        "3129573174.522287",
    ),
    (
        "Block height 288288",
        "000000000000000119ded60e1041481b96257dbcb43889e9e7c5f9e410663f6b",
        0x19012026,
        "3815723798.81463",
    ),
    (
        "Block height 290304",
        "0000000000000000c08e820bacf03c9abc92a66de4c95daa76ee39af3d3e16de",
        0x190102b1,
        "4250217919.869535",
    ),
    (
        "Block height 292320",
        "000000000000000063306b17182f398a454d72736b38a30d0a7d49aaf898383f",
        0x1900db99,
        "5006860589.2054",
    ),
    (
        "Block height 294336",
        "00000000000000009bd3ff597773e2fb16310491f6c1e69c85938f51b561d663",
        0x1900b3aa,
        "6119726089.128147",
    ),
    (
        "Block height 296352",
        "00000000000000003decdbb5f3811eab3148fbc29d3610528eb3b50d9ee5723f",
        0x19009d8c,
        "6978842649.592383",
    ),
    (
        "Block height 298368",
        "0000000000000000092dbe12467f95d456d9bd7ff12b88dc3bcdd28b4a7aa159",
        0x1900896c,
        "8000872135.968163",
    ),
    (
        "Block height 300384",
        "0000000000000000646aeda800ee605632799ead6257976b3805c66682b4d34e",
        0x187c3053,
        "8853416309.1278",
    ),
    (
        "Block height 302400",
        "0000000000000000472132c4daaf358acaf461ff1c3e96577a74e5ebf91bb170",
        0x18692842,
        "10455720138.48484",
    ),
    (
        "Block height 304416",
        "00000000000000000ead30f2a70f979a6b07f841ca05302497a92b3c9a9488a3",
        0x185d859a,
        "11756551916.90395",
    ),
    (
        "Block height 306432",
        "00000000000000000d03d0dc77d39f1657e14f9d66ba9b46fb5a9562aaa1c9e9",
        0x1851aba2,
        "13462580114.52534",
    ),
    (
        "Block height 308448",
        "00000000000000000828e7f7f643a00d1449041dfff89775139ab8e5ed2d7d58",
        0x18415fd1,
        "16818461371.16111",
    ),
    (
        "Block height 310464",
        "000000000000000012b7c91c612ccd028dd650b78018ed1c271e871ae87500e2",
        0x183f6be6,
        "17336316978.50783",
    ),
    (
        "Block height 312480",
        "00000000000000002e50dde7a70f58018886ceb04ce3285e504c59e58190193b",
        0x183aaea2,
        "18736441558.31024",
    ),
    (
        "Block height 314496",
        "000000000000000030e597a72386c512d830b08ecc70b254f46033fd06f2bf93",
        0x1837ba62,
        "19729645940.57713",
    ),
    (
        "Block height 316512",
        "00000000000000000dc32808fc3f3f0ce02c8c7d17258ad6e651b8ba1e02384d",
        0x182e1c58,
        "23844670038.8033",
    ),
    (
        "Block height 318528",
        "000000000000000020b33e5d35f4eff42926dabb14ab4f6560a424d0c94d9ecc",
        0x182815ee,
        "27428630902.25787",
    ),
    (
        "Block height 320544",
        "000000000000000003d8844f0f85abf23ac688daf6e7db448bb12c0153554531",
        0x1824dbe9,
        "29829733124.04042",
    ),
    (
        "Block height 322560",
        "000000000000000002df2dd9d4fe0578392e519610e341dd09025469f101cfa1",
        0x181fb893,
        "34661425923.97694",
    ),
    (
        "Block height 324576",
        "00000000000000000929d6985e904154c98e113450fb31aa715f565ef7993226",
        0x181f6973,
        "35002482026.13323",
    ),
    (
        "Block height 326592",
        "00000000000000001619e7bd45b3090941bcc08bd7a07357ab974bf7627b65c2",
        0x181e8dc0,
        "35985640265.07623",
    ),
    (
        "Block height 328608",
        "000000000000000010aaf4c9efd94fc5bdcef96688222c9a3fff6b85df524531",
        0x181bc330,
        "39603666252.41841",
    ),
    (
        "Block height 330624",
        "00000000000000000cb582b07e2efe2007fb21030049b582d81c1ffe80185600",
        0x181b4861,
        "40300030327.8914",
    ),
    (
        "Block height 332640",
        "000000000000000005050188c4b38ab58644e1b69aad22dcc99e819d1deb0bb5",
        0x181b7b74,
        "40007470271.27126",
    ),
    (
        "Block height 334656",
        "00000000000000000c8a9d89a727e0b123ccf51f083a81524c44411fc554bb89",
        0x181bdd7c,
        "39457671307.13873",
    ),
    (
        "Block height 336672",
        "00000000000000000ee5a3a4e7ff72097c32f91ae2fa039d7ca21ba533913022",
        0x181b0dca,
        "40640955016.57649",
    ),
    (
        "Block height 338688",
        "000000000000000017dfe3f5ebf13fdcf41b255ad0c3da4fc880745a221bf959",
        0x1819012f,
        "43971662056.08958",
    ),
    (
        "Block height 340704",
        "000000000000000017fa101a33cd4db056343c28ba14f9fe63710f234c094c6f",
        0x181aa3c0,
        "41272873894.69702",
    ),
    (
        "Block height 342720",
        "00000000000000000f9cfece8494800d3dcbf9583232825da640c8703bcd27e7",
        0x1818bb87,
        "44455415962.3438",
    ),
    (
        "Block height 344736",
        "00000000000000001097f043cca218169e00623c9962b25a0b159eaca2d8ca25",
        0x18178d3a,
        "46684376316.86029",
    ),
    (
        "Block height 346752",
        "00000000000000000de2ec3c6855a2c20160b6693d63d1a0b774ca9630b692bc",
        0x18172ec0,
        "47427554950.6483",
    ),
    (
        "Block height 348768",
        "0000000000000000145865530e632fdcc732e2309645d759d738c7c9f4edb503",
        0x181788f2,
        "46717549644.70642",
    ),
    (
        "Block height 350784",
        "000000000000000010f21b105b759b2c1df9c20f749ecd9d6e410a06a9d82b2a",
        0x18163c71,
        "49446390688.24144",
    ),
    (
        "Block height 352800",
        "00000000000000000b28d69f3103a15e246dc0c72e4eec99b40f351856eccfd2",
        0x181717f0,
        "47610564513.47126",
    ),
    (
        "Block height 354816",
        "0000000000000000029d89edce1555621ea75272d4e44ca90ec79a89e1dd8fab",
        0x181713dd,
        "47643398017.80344",
    ),
    (
        "Block height 356832",
        "000000000000000008f4a7a3c554a897989b5484075377b4e0861bb4a89a0829",
        0x181686f5,
        "48807487244.68138",
    ),
    (
        "Block height 358848",
        "0000000000000000052bb0c3c8d6c1fba431e7c9c05a625f6b42c68e1173b789",
        0x18171a8b,
        "47589591153.62501",
    ),
    (
        "Block height 360864",
        "000000000000000000a7ba82574da4f0713ea1b4044bb473c1ae3902f9b73a6f",
        0x18162043,
        "49692386354.89384",
    ),
    (
        "Block height 362880",
        "000000000000000014898b8e6538392702ffb9450f904c80ebf9d82b519a77d5",
        0x1816418e,
        "49402014931.22746",
    ),
    (
        "Block height 364896",
        "00000000000000000d93a9b96ac9fe19918627482dbe87c3aadf42453159e1ab",
        0x181586c8,
        "51076366303.48193",
    ),
    (
        "Block height 366912",
        "000000000000000002447e2b32255e01bab52fb80615913b128d03b8df5c4da0",
        0x18150815,
        "52278304845.59168",
    ),
    (
        "Block height 368928",
        "000000000000000011da147fbbbf817793cac08e33e243db8728e84b2fc05837",
        0x1814dd04,
        "52699842409.34701",
    ),
    (
        "Block height 370944",
        "00000000000000000a169260c995869aa029ae29c701ff655f8527ae7a7d4cad",
        0x181443c4,
        "54256630327.88996",
    ),
    (
        "Block height 372960",
        "00000000000000000d2d3c9ba1b552e9855f7e1ebded0859b3f8e14b0f05b0f3",
        0x18134dc1,
        "56957648455.01001",
    ),
    (
        "Block height 374976",
        "000000000000000008aec102f67979e6c7e14b9690fc856d3728e48f9c2a0930",
        0x181287ba,
        "59335351233.86657",
    ),
    (
        "Block height 376992",
        "0000000000000000021a4323000720f49619762e302aa921f214cd8a4adbfdb4",
        0x18121472,
        "60813224039.44035",
    ),
    (
        "Block height 379008",
        "00000000000000000e018e0f8258fd1f6f27d584a513b94ef0a3045a1363a692",
        0x18120f14,
        "60883825480.09828",
    ),
    (
        "Block height 381024",
        "00000000000000000bc746cbe3ceb043400575fbdac96d40c8db74e929401091",
        0x1811a954,
        "62253982449.76082",
    ),
    (
        "Block height 383040",
        "00000000000000000a974fa1a3f84055ad5ef0b2f96328bc96310ce83da801c9",
        0x1810b289,
        "65848255179.70261",
    ),
    (
        "Block height 385056",
        "000000000000000007997cac5415cce2dddd7a878508f901fef05452cfe591e2",
        0x180f1e76,
        "72722780642.54718",
    ),
    (
        "Block height 387072",
        "000000000000000002391d66ffb9efb44baf3736f03f998956eea30be87679a0",
        0x180de64f,
        "79102380900.22598",
    ),
    (
        "Block height 389088",
        "00000000000000000ba0a2074428c20b60dd96ca0fc26eb4ceec555b06bbc290",
        0x180bc409,
        "93448670796.32381",
    ),
    (
        "Block height 391104",
        "0000000000000000063067ef2e7513ea864d297c76f15e4af4caeb46c9af5618",
        0x180a9591,
        "103880340815.4559",
    ),
    (
        "Block height 393120",
        "000000000000000009534c3d754ee4b844ac174534f33a7d3cece4b26a78bc95",
        0x1809b31b,
        "113354299801.4711",
    ),
    (
        "Block height 395136",
        "000000000000000001b7b4dd9ea535a1f5bb8f3d3330dc161be2bf98fed493a0",
        0x180928f0,
        "120033340651.237",
    ),
    (
        "Block height 397152",
        "000000000000000001fb0d16d9a1bca38cae63fb95fdb0ebb384351a3f953dd8",
        0x1807a114,
        "144116447847.3487",
    ),
    (
        "Block height 399168",
        "000000000000000002ee8708b6c5ca0b4e055fbeed16189af256ed8a8d4b181d",
        0x1806b99f,
        "163491654908.9593",
    ),
    (
        "Block height 401184",
        "000000000000000002e9533a4fe03bb251b3fdb30ffaa384aad133b7fae594cf",
        0x1806f0a8,
        "158427203767.3917",
    ),
    (
        "Block height 403200",
        "000000000000000000c4272a5c68b4f55e5af734e88ceab09abf73e9ac3b6d01",
        0x1806a4c3,
        "165496835118.2263",
    ),
    (
        "Block height 405216",
        "000000000000000006969473ee3a2126d9a953ad00eee6443b4d2d2e0881fc07",
        0x180696f4,
        "166851513282.7772",
    ),
    (
        "Block height 407232",
        "000000000000000002b7ccc541f63f7dc041f5baec3259a4e252507811d5c75d",
        0x1806274b,
        "178678307671.6884",
    ),
    (
        "Block height 409248",
        "000000000000000005c7e043332761d79f6de7d065af0d062d2276220c0393cf",
        0x18062776,
        "178659257772.5273",
    ),
    (
        "Block height 411264",
        "000000000000000002619c83c8084b8cfa737f5bf8936ea7a44270d9aa7adb98",
        0x1805a8fa,
        "194254820283.444",
    ),
    (
        "Block height 413280",
        "00000000000000000546843240d1ddc1d6f3b1fd85c4b0f4ad2123708bb669cc",
        0x18058436,
        "199312067531.243",
    ),
    (
        "Block height 415296",
        "000000000000000004c4e66066e75867345a668cf17f8e2f84c048ecf6303192",
        0x18059ba0,
        "196061423939.65",
    ),
    (
        "Block height 417312",
        "0000000000000000047b023f02222a66865484f6e990af65061f0b3cc1ed319f",
        0x18053fd6,
        "209453158595.381",
    ),
    (
        "Block height 419328",
        "000000000000000004a1b34462cb8aeebd5799177f7a29cf28f2d1961716b5b5",
        0x180526fd,
        "213398925331.3239",
    ),
    (
        "Block height 421344",
        "000000000000000000a3b691d6bc7b772b8035a2104ca168b02e3adac6be52d9",
        0x18052669,
        "213492501107.5134",
    ),
    (
        "Block height 423360",
        "000000000000000001630546cde8482cc183708f076a5e4d6f51cd24518e8f85",
        0x18057228,
        "201893210853.059",
    ),
    (
        "Block height 425376",
        "000000000000000000f1f397a3e6744d9db44bd4335ba541b139b84510f15a02",
        0x18050edc,
        "217375482757.2376",
    ),
    (
        "Block height 427392",
        "000000000000000001d689458332df92b48f7a797acde5ed93251cc33c10501f",
        0x1804fb08,
        "220755908330.3723",
    ),
    (
        "Block height 429408",
        "000000000000000000917ec6fe1ace9d539db88d256550768fa292ec5cd75096",
        0x1804de5e,
        "225832872179.4596",
    ),
    (
        "Block height 431424",
        "0000000000000000025a36627560ff77a9549de4e269f6fcd8b21a0a4589878b",
        0x18048ed4,
        "241227200229.991",
    ),
    (
        "Block height 433440",
        "000000000000000002ccd910a5991c4e97e3bfbe08b5b75992c5337cedc0c714",
        0x180440c4,
        "258522748404.5154",
    ),
    (
        "Block height 435456",
        "00000000000000000082ed5c599748dbaf59b084445c3f0c107fef194fe9009b",
        0x180455d2,
        "253618246641.4895",
    ),
    (
        "Block height 437472",
        "000000000000000003c75c23f1444676c6832d45badd6ae89b8d1903d92563b7",
        0x18045174,
        "254620187304.0614",
    ),
    (
        "Block height 439488",
        "000000000000000001a4da46f04329a0790734e22172fe14a2c8cf973e8c9d29",
        0x1803e6d4,
        "281800917193.1958",
    ),
    (
        "Block height 441504",
        "000000000000000000c08d8182b7ebb7b95d47f96d906befd2add9f2640b143b",
        0x1803d589,
        "286765766820.5504",
    ),
    (
        "Block height 443520",
        "00000000000000000345d0c7890b2c81ab5139c6e83400e5bed00d23a1f8d239",
        0x18038b85,
        "310153855703.4333",
    ),
    (
        "Block height 445536",
        "0000000000000000016067670c2a98f24abaaf762f1427f951c824460ebf256d",
        0x180375ff,
        "317688400354.0338",
    ),
    (
        "Block height 447552",
        "000000000000000001a151aaf940f95cfe16db0d2522fb0209106ce6ecbe83c2",
        0x18034379,
        "336899932795.8077",
    ),
    (
        "Block height 449568",
        "000000000000000002884993a2b7306aa7b2af94b6ffe00bc7c689738f7816c6",
        0x1802cc47,
        "392963262344.3704",
    ),
    (
        "Block height 451584",
        "0000000000000000021faf765242dc0734b4bd33f1459d74616aa9004e331bb5",
        0x18029ab9,
        "422170566883.8369",
    ),
    (
        "Block height 453600",
        "000000000000000001b550160c047005c24f8e41bfccfc07d4f0b9d7bb5a9492",
        0x18027e93,
        "440779902286.5892",
    ),
    (
        "Block height 455616",
        "000000000000000001f87b34342c67eadb07a5c48a6127ba1628dd43c0b97b45",
        0x180262df,
        "460769358090.7142",
    ),
    (
        "Block height 457632",
        "000000000000000000c8577049eef346135bc3da57a0e5d84844c21b57cc2d4d",
        0x18024fb1,
        "475705205061.6292",
    ),
    (
        "Block height 459648",
        "00000000000000000193d1eb4d55118ad5f674940689f5bf28b9912766472b3d",
        0x1802335a,
        "499635929816.6675",
    ),
    (
        "Block height 461664",
        "00000000000000000094784c391a6f63e8ab26099a427b053015f8c6666f7445",
        0x18021c73,
        "520808749422.1398",
    ),
    (
        "Block height 463680",
        "000000000000000000431a2f4619afe62357cd16589b638bb638f2992058d88e",
        0x18021b3e,
        "521974519553.6282",
    ),
    (
        "Block height 465696",
        "000000000000000000d2d8803ee666293b2baa54fce5fdff55b169c069906405",
        0x1801f6a7,
        "559970892890.8381",
    ),
    (
        "Block height 467712",
        "0000000000000000004ba38a4f8c71370eb5a2eca4addafb745dd333e68dd9e2",
        0x1801d854,
        "595921917085.416",
    ),
    (
        "Block height 469728",
        "0000000000000000018df99526ab63ae0a43ad207cd9a022a88acdc9b21b0954",
        0x18019eaf,
        "678760110082.9902",
    ),
    (
        "Block height 471744",
        "0000000000000000012a85f9010f0e2cf696408300918f4b5df8ddd8809102a2",
        0x18018b7e,
        "711697198173.7566",
    ),
    (
        "Block height 473760",
        "000000000000000000802ba879f1b7a638dcea6ff0ceb614d91afc8683ac0502",
        0x18018d30,
        "708659466230.332",
    ),
    (
        "Block height 475776",
        "00000000000000000107381c73a65cd4e845d4bb1ba25d123607dfd8e134fb87",
        0x18015ddc,
        "804525194568.1318",
    ),
    (
        "Block height 477792",
        "00000000000000000016ba7786309176445b838b36a16bd1ef3c3e3020473206",
        0x18014735,
        "860221984436.2223",
    ),
    (
        "Block height 479808",
        "0000000000000000012e6060980c6475a9a8e62a1bf44b76c5d51f707d54522c",
        0x180130e0,
        "923233068448.9053",
    ),
    (
        "Block height 481824",
        "0000000000000000001c8018d9cb3b742ef25114f27563e3fc4a1902167f9893",
        0x18013ce9,
        "888171856257.3206",
    ),
    (
        "Block height 483840",
        "0000000000000000008e5d72027ef42ca050a0776b7184c96d0d4b300fa5da9e",
        0x1801310b,
        "922724699725.9628",
    ),
    (
        "Block height 485856",
        "0000000000000000002671055718b4d50555eda2e3a8acd019460a4af0697313",
        0x1800ff18,
        "1103400932964.292",
    ),
    (
        "Block height 487872",
        "000000000000000000462faf5634a9ce155855051609c2b0e32f841fbc8d309a",
        0x1800fa73,
        "1123863285132.967",
    ),
    (
        "Block height 489888",
        "0000000000000000006c4cee77fe5e723d5fb7f3deb0e92740f0845abc321015",
        0x1800eb30,
        "1196792694098.793",
    ),
    (
        "Block height 491904",
        "000000000000000000b7e385cac200c058ede4b7e732855ab94a9942361ccf8e",
        0x1800c1bd,
        "1452839779145.919",
    ),
    (
        "Block height 493920",
        "00000000000000000057d80ab2ba6fdcd29234d4aaeb596330378aebfc5b31a5",
        0x1800ce4b,
        "1364422081125.147",
    ),
    (
        "Block height 495936",
        "0000000000000000004f4e400ab04730c6c53cd45c4d2d7360c33c77c6b9f00e",
        0x1800d0f6,
        "1347001430558.57",
    ),
    (
        "Block height 497952",
        "000000000000000000139d2fc37814f5efdc637a6c8e1b202f9ee12365b01403",
        0x1800b0ed,
        "1590896927258.079",
    ),
    (
        "Block height 499968",
        "000000000000000000296e10eb4987c4eb9b7ba0841102dec4480e5d6b89acb5",
        0x18009645,
        "1873105475221.611",
    ),
    (
        "Block height 501984",
        "0000000000000000005c14c4abc42feddb34bf86688760d3978ae36da7e32451",
        0x180091c1,
        "1931136454487.716",
    ),
    (
        "Block height 504000",
        "0000000000000000006cd44d7a940c79f94c7c272d159ba19feb15891aa1ea54",
        0x177e578c,
        "2227847638503.628",
    ),
    (
        "Block height 506016",
        "000000000000000000258fe79c8b891a7cecdf96196c6c9b2e609318c7ad95c9",
        0x176c2146,
        "2603077300218.593",
    ),
    (
        "Block height 508032",
        "00000000000000000018e2d304128766f69359ca69bf1d6b0f2d6fd238ea218c",
        0x1761e9f8,
        "2874674234415.941",
    ),
    (
        "Block height 510048",
        "00000000000000000000906ae43e5e20371147f0da793d2642508271c3124e16",
        0x175d97dc,
        "3007383866429.732",
    ),
    (
        "Block height 512064",
        "0000000000000000000982261907543d73f7d07eb9a18ae2b27525da3c6e33b5",
        0x175589a3,
        "3290605988755.001",
    ),
    (
        "Block height 514080",
        "0000000000000000001118775a096ca034398e97e5c9103d4f9fce8bf11873a4",
        0x17514a49,
        "3462542391191.563",
    ),
    (
        "Block height 516096",
        "0000000000000000002499e3989b78ec7209b24f62514587267e08110ceee964",
        0x17502ab7,
        "3511060552899.72",
    ),
    (
        "Block height 518112",
        "0000000000000000002fa1c76230e3bd064d6527e5dd381c3bcef5249c32a626",
        0x1749500d,
        "3839316899029.672",
    ),
    (
        "Block height 520128",
        "0000000000000000000834bbe36f81bf8cbde1eec39bf535f8c1c0f4859a1f82",
        0x1745fb53,
        "4022059196164.954",
    ),
    (
        "Block height 522144",
        "0000000000000000002ff87d63c62cb421f0f935d58677e02d8feae6a0a2e9fe",
        0x1743eca9,
        "4143878474754.188",
    ),
    (
        "Block height 524160",
        "00000000000000000009d1e9bee76d334347060c6a2985d6cbc5c22e48f14ed2",
        0x17415a49,
        "4306949573981.513",
    ),
    (
        "Block height 526176",
        "00000000000000000009978b58e807d626b81d4c224813a2d2fd51a1a8682f2f",
        0x1738f841,
        "4940704885521.827",
    ),
    (
        "Block height 528192",
        "000000000000000000063df1c3a28e5d78b941e7a48cd8466f6265d768b5416a",
        0x17376f56,
        "5077499034879.017",
    ),
    (
        "Block height 530208",
        "0000000000000000002999e6f0537a1707b027a7ccdce1723700d51b1400be30",
        0x17347a28,
        "5363678461481.357",
    ),
    (
        "Block height 532224",
        "0000000000000000003053b2dad316ce2fc65e8ac63d59d0752d980e43934ad0",
        0x17365a17,
        "5178671069072.251",
    ),
    (
        "Block height 534240",
        "00000000000000000010edacfe56dc4f58436afeadc0f9d203bed8aa4824e06f",
        0x172f4f7b,
        "5949437371609.53",
    ),
    (
        "Block height 536256",
        "000000000000000000262e508512ce2e6a018e181fb2e5efe048a4e01d21fa7a",
        0x172c0da7,
        "6389316883511.965",
    ),
    (
        "Block height 538272",
        "00000000000000000004f11858464cc6113248537a01e628324968b499848a60",
        0x1729d72d,
        "6727225469722.534",
    ),
    (
        "Block height 540288",
        "00000000000000000027a5c0246882e2822da309358f93189a408b1bf46a767e",
        0x172819a1,
        "7019199231177.173",
    ),
    (
        "Block height 542304",
        "00000000000000000014197b06c6bbf9f5aa1eeb8ff529361cd161dce91d19cc",
        0x17275a1f,
        "7152633351906.413",
    ),
    (
        "Block height 544320",
        "0000000000000000000a5e9b5e4fbee51f3d53f31f40cd26b8e59ef86acb2ebd",
        0x1725c191,
        "7454968648263.241",
    ),
    (
        "Block height 546336",
        "0000000000000000000d8ff2d0a2b90e2edf0ec7830ed7d5805e4d8a5cf4bd84",
        0x17272fbd,
        "7182852313938.317",
    ),
    (
        "Block height 548352",
        "00000000000000000013f4778796947335e3ab173b555259675be50cdfe875fa",
        0x17272d92,
        "7184404942701.792",
    ),
    (
        "Block height 550368",
        "00000000000000000015df840aeb481ff27b44f2cfa14f81886e98f25395ebdf",
        0x172a4e2f,
        "6653303141405.96",
    ),
    (
        "Block height 552384",
        "00000000000000000015038a38aa780723a79ae8fc6f1881240dac31aea9189d",
        0x1731d97c,
        "5646403851534.721",
    ),
    (
        "Block height 554400",
        "000000000000000000043c0b1ba0e06f1569ff7cebca6a78a84f4025712067ae",
        0x17371ef4,
        "5106422924659.822",
    ),
    (
        "Block height 556416",
        "0000000000000000002a531985d49cdb5adcd1db0578845a233a3a2cfdefdf8f",
        0x173218a5,
        "5618595848853.279",
    ),
    (
        "Block height 558432",
        "00000000000000000021ac236d0b29b4467f99c2c8783032451ba7b735045e3c",
        0x172fd633,
        "5883988430955.408",
    ),
    (
        "Block height 560448",
        "00000000000000000020adeb95048ff41daac22d2dd97414fd5c47cdc391923a",
        0x17306835,
        "5814661935891.805",
    ),
    (
        "Block height 562464",
        "0000000000000000000db7442b5662bbd980d7c2db1aef2ca925917ae392df11",
        0x172e6f88,
        "6061518831027.271",
    ),
    (
        "Block height 564480",
        "0000000000000000002567dc317da20ddb0d7ef922fe1f9c2375671654f9006c",
        0x172e5b50,
        "6071846049920.752",
    ),
    (
        "Block height 566496",
        "00000000000000000015fea169c62eb0a1161aba36932ca32bc3785cbb3480bf",
        0x172e6117,
        "6068891541676.553",
    ),
    (
        "Block height 568512",
        "0000000000000000001debd424683ee6c16b05a441309f96925dad309af03e80",
        0x172c1f6c,
        "6379265451411.053",
    ),
    (
        "Block height 570528",
        "0000000000000000000d4833adbfb465d4cfb57c2918b830db228cf1b217d99f",
        0x172c071d,
        "6393023717201.863",
    ),
    (
        "Block height 572544",
        "00000000000000000004b26b4dcf718a920a7ab5d2a47b8fe31aec4314c41122",
        0x172c4e11,
        "6353030562983.983",
    ),
    (
        "Block height 574560",
        "00000000000000000008c8427670a65dec4360e88bf6c8381541ef26b30bd8fc",
        0x1729ff38,
        "6702169884349.173",
    ),
    (
        "Block height 576576",
        "0000000000000000001721f58deb88b0710295a02551f0dde1e2e231a15f1882",
        0x1729fb45,
        "6704632680587.417",
    ),
    (
        "Block height 578592",
        "00000000000000000001791f463d849ce5363d751c91f7d3cd2ff18981ae221d",
        0x1725bb76,
        "7459680720542.296",
    ),
    (
        "Block height 580608",
        "00000000000000000005b9056e846784da78f5c945d5434cbadb13c454e31ad7",
        0x1725fd03,
        "7409399249090.253",
    ),
    (
        "Block height 582624",
        "0000000000000000001a4efc92b3827640a97714a45900b8ad3a682f69b10c8b",
        0x1723792c,
        "7934713219630.606",
    ),
    (
        "Block height 584640",
        "0000000000000000000e5af6f531133eb548fe3854486ade75523002a1a27687",
        0x171f0d9b,
        "9064159826491.41",
    ),
    (
        "Block height 586656",
        "000000000000000000063108ecc1f03f7fd1481eb20f97307d532a612bc97f04",
        0x171f3a08,
        "9013786945891.682",
    ),
    (
        "Block height 588672",
        "0000000000000000001c2a0a3aa902828a10be3588871b01699232c58de04d70",
        0x171c3039,
        "9985348008059.555",
    ),
    (
        "Block height 590688",
        "0000000000000000000bab9600a8e7593e2b13ea061c88f1c107a282ee75830b",
        0x171ba3d1,
        "10183488432890",
    ),
    (
        "Block height 592704",
        "0000000000000000000066adb5f809023af42cca28d3e5d377191e50b2c511d7",
        0x171a213e,
        "10771996663680.4",
    ),
    (
        "Block height 594720",
        "0000000000000000000adbae4bf35fa89a6519e3250fe09bbd4a4eaa2a46e0d8",
        0x1717abf5,
        "11890594958795.76",
    ),
    (
        "Block height 596736",
        "00000000000000000015d2e26e7496ee06e8c3b783ece165f1d60c38923b23b8",
        0x17160f24,
        "12759819404408.79",
    ),
    (
        "Block height 598752",
        "00000000000000000008dcd17d53eadf2676ce89bf455fb37030ba41b43d1140",
        0x1715a35c,
        "13008091666971.9",
    ),
    (
        "Block height 600768",
        "0000000000000000000983a15a2735b4f37861c4019d97200820cd190f28dba5",
        0x17148edf,
        "13691480038694.45",
    ),
    (
        "Block height 602784",
        "000000000000000000119839f8a9f5a021a5cd442fafd6e712089bb5cf238a8d",
        0x171620d1,
        "12720005267390.51",
    ),
    (
        "Block height 604800",
        "00000000000000000012145f8ffa7218d2d04ca66b61835a2a5eaec33dffc098",
        0x1715b23e,
        "12973235968799.78",
    ),
    (
        "Block height 606816",
        "00000000000000000005857209fc152c7bfe5b721fed39b503463b118674ffd1",
        0x1715dbd2,
        "12876842089682.48",
    ),
    (
        "Block height 608832",
        "00000000000000000002dce191b529017edae3c76d91ab21f757d156daebf43f",
        0x1715bcd0,
        "12948593420946.38",
    ),
    (
        "Block height 610848",
        "0000000000000000000657ec7477dece018c07b534be94edfff9aed1068a7613",
        0x171465f2,
        "13798783827516.42",
    ),
    (
        "Block height 612864",
        "0000000000000000000650bc59cd17d268dfaa1c6768fd890d32c1c7b38503d2",
        0x17130c78,
        "14776367535688.64",
    ),
    (
        "Block height 614880",
        "00000000000000000004fec124eaa3f2e893d2cc26a7c22a547b270b824882ef",
        0x171232ff,
        "15466098935554.65",
    ),
    (
        "Block height 616896",
        "00000000000000000004f0d5a56473157602071a4bb112623b1211536d40e69b",
        0x17121ad4,
        "15546745765529.37",
    ),
    (
        "Block height 618912",
        "00000000000000000003fa80fb38019a948f5eec1e6e285a8d1eaec21d197c5f",
        0x17122cbc,
        "15486913440292.87",
    ),
    (
        "Block height 620928",
        "0000000000000000000ef67350dd906ef03d730d8105957b450475066a1da75a",
        0x17110119,
        "16552923967337.23",
    ),
    (
        "Block height 622944",
        "000000000000000000093ae093fe07468673202890e89514a435c0028610a759",
        0x17143b41,
        "13912524048945.91",
    ),
    (
        "Block height 624960",
        "00000000000000000010a34de0c20440b6804f61549e1c1b18d0b80afb589d6e",
        0x171320bc,
        "14715214060656.53",
    ),
    (
        "Block height 626976",
        "0000000000000000000a8d8486b649b3f4e989b4491716ba53e652a3e362f0a0",
        0x1711a333,
        "15958652328578.42",
    ),
    (
        "Block height 628992",
        "00000000000000000008a8e850ca0b74ec52e3f31eeb04da892aa64e0dc59e45",
        0x17117a39,
        "16104807485529.38",
    ),
    (
        "Block height 631008",
        "0000000000000000000afe86c660a568a750c603f72dba13b32abb1f31125188",
        0x171297f6,
        "15138043247082.88",
    ),
    (
        "Block height 633024",
        "0000000000000000000041081b7d827cfd66f4b79c5c44007d7c11a45fb649ca",
        0x17147f35,
        "13732352106018.34",
    ),
    (
        "Block height 635040",
        "0000000000000000000e0862a184c9cabd17392661b46124203899707bf93b2b",
        0x1711d4f2,
        "15784744305477.41",
    ),
    (
        "Block height 637056",
        "000000000000000000075dff6bbc582ead3cf81faab124e591c7e230ed200754",
        0x1711d519,
        "15784217546288.15",
    ),
    (
        "Block height 639072",
        "00000000000000000007b80b8a4de32c55aa2af710f8fd6bb37bc0057bbed840",
        0x17103a15,
        "17345948872516.06",
    ),
    (
        "Block height 641088",
        "0000000000000000000316eb7603f5b29c144d481ecbfd497540523a414685ef",
        0x1710b4f8,
        "16847561611550.27",
    ),
    (
        "Block height 643104",
        "00000000000000000001362ab47e135a04f93da7bc50e0fbe669a4eea3c7535d",
        0x17109bac,
        "16947802333946.61",
    ),
    (
        "Block height 645120",
        "000000000000000000015d97e4f3e544f5285016a6d027985f85ea4cab47e54c",
        0x171007ea,
        "17557993035167.3",
    ),
    (
        "Block height 647136",
        "000000000000000000003355843ef2eefc24ef9a55a9ac5162f5a968552003c2",
        0x17103a12,
        "17345997805929.09",
    ),
    (
        "Block height 649152",
        "0000000000000000000c65910133493fb8ecb701c56d2ae8fd37cfde98b1acb8",
        0x170e92aa,
        "19314656404097",
    ),
    (
        "Block height 651168",
        "00000000000000000007e2b2a445606b0fcfe3768efe4c3840efa6a1e8f94715",
        0x170e95de,
        "19298087186262.61",
    ),
    (
        "Block height 653184",
        "000000000000000000092d577cc673bede24b6d7199ee69c67eeb46c18fc978c",
        0x170e134e,
        "19997335994446.11",
    ),
    (
        "Block height 655200",
        "0000000000000000000be6439455cefcb61e62eb9b0f47f2c99d2de2ce8dd144",
        0x1710c433,
        "16787779609932.66",
    ),
    (
        "Block height 657216",
        "00000000000000000004a6d259923e7eaad54d1ab1796d52c869ab1863191734",
        0x170ffedd,
        "17596801059571.43",
    ),
    (
        "Block height 659232",
        "0000000000000000000928fb11adc05cb38a614825768c586dc867501af56de1",
        0x170eb156,
        "19157154724710.14",
    ),
    (
        "Block height 661248",
        "00000000000000000004ecefaacd7051fdd8586f39434679d506665c472715ad",
        0x170f1372,
        "18670168558399.59",
    ),
    (
        "Block height 663264",
        "0000000000000000000094b957dc1f67619089c19ff471937623694ec69bc671",
        0x170f2217,
        "18599593048299.49",
    ),
    (
        "Block height 665280",
        "00000000000000000009ebabc95533bbe0e40adecee879449db291237b3db350",
        0x170da8a1,
        "20607418304385.63",
    ),
    (
        "Block height 667296",
        "0000000000000000000b4ee841f48d91eb555ffac11514f9aa4b26b859e7d3b0",
        0x170d8457,
        "20823531150111.52",
    ),
    (
        "Block height 669312",
        "0000000000000000000beb9d24f999168c79fa58394868f9fcc5367c28f137dc",
        0x170d21b9,
        "21434395961348.92",
    ),
    (
        "Block height 671328",
        "00000000000000000002dcfc81932274802b686f410c4d4621693c7f297bd5a7",
        0x170cf4e3,
        "21724134900047.27",
    ),
    (
        "Block height 673344",
        "0000000000000000000c75abe69a999b4a2ee312449c604298f42903a7f73d52",
        0x170d1f8c,
        "21448277761059.71",
    ),
    (
        "Block height 675360",
        "0000000000000000000ab0e08613cd1288780f475db41e278bd37514254edb33",
        0x170cdf6f,
        "21865558044610.55",
    ),
    (
        "Block height 677376",
        "0000000000000000000a1b463e60dad4c6ad3329e107c8297ed43592d2787e50",
        0x170c2a48,
        "23137439666472.05",
    ),
    (
        "Block height 679392",
        "000000000000000000006c1c6b4f9a693ff7ec4f996ea62be6ee11bcefde9db2",
        0x170bef93,
        "23581981443663.85",
    ),
    (
        "Block height 681408",
        "000000000000000000020210114d7faf44223e1d620991e468af964514ff96e3",
        0x170da863,
        "20608845737768.16",
    ),
    (
        "Block height 683424",
        "0000000000000000000ae59ab3f2bfe8582be8aeecce3c623a08b98e9bc2a5b9",
        0x170b3ce9,
        "25046487590083.27",
    ),
    (
        "Block height 685440",
        "000000000000000000016f0484972d135afba541c837d0c07c1530ffeee293cd",
        0x170d5f7b,
        "21047730572451.55",
    ),
    (
        "Block height 687456",
        "0000000000000000000a8efe0a1e90a140eba888af012c95571367b2ceea50ac",
        0x170e1ef9,
        "19932791027262.74",
    ),
    (
        "Block height 689472",
        "000000000000000000124347f70edac39e58d972c79086d860929baf07e455aa",
        0x171398ce,
        "14363025673659.96",
    ),
    (
        "Block height 691488",
        "00000000000000000007042e2b204c139c2f2b0642b3912b7ccf9c524f27b6d1",
        0x17149624,
        "13672594272814.14",
    ),
    (
        "Block height 693504",
        "000000000000000000064a9b16286a2fda7d0783757c3ff4957b699df545204d",
        0x17136aa2,
        "14496442856349.12",
    ),
    (
        "Block height 695520",
        "00000000000000000005d6d75e158a8a537daf5ab9516c4f677ca0f62c32f514",
        0x1712180b,
        "15556093717702.55",
    ),
    (
        "Block height 697536",
        "000000000000000000084fd70c0f4b9569c3775f3588be0b277e96706f2927e7",
        0x170ffaa0,
        "17615033039278.88",
    ),
    (
        "Block height 699552",
        "0000000000000000000e8989c9ac71fbc912ceef70a8ec4685644243f44a87b4",
        0x170f48e4,
        "18415156832118.24",
    ),
    (
        "Block height 701568",
        "00000000000000000000d62401a0d63bd580401bcec35d52695bb0efecbb2ce4",
        0x170ed0eb,
        "18997641161758.95",
    ),
    (
        "Block height 703584",
        "00000000000000000004288838ebecdcc4c87fb5a9a3c69437c351bb87410d51",
        0x170e2632,
        "19893045048575.13",
    ),
    (
        "Block height 705600",
        "0000000000000000000d37dfef7fe1c7bd22c893dbe4a94272c8cf556e40be99",
        0x170e0408,
        "20082460130830.84",
    ),
    (
        "Block height 707616",
        "00000000000000000002c26934496974adf77b74332c6e9ada689e0b0212a302",
        0x170cfecf,
        "21659344833264.85",
    ),
    (
        "Block height 709632",
        "0000000000000000000687bca986194dc2c1f949318629b44bb54ec0a94d8244",
        0x170c69ea,
        "22674148233453.11",
    ),
    (
        "Block height 711648",
        "0000000000000000000c85eb12ec078d2e9924ca905780e0312443699fa631fc",
        0x170c9a13,
        "22335659268936.39",
    ),
    (
        "Block height 713664",
        "00000000000000000007e0f205011034fcb6577b0840b35fcabc4f5a77645f35",
        0x170ba21f,
        "24195286980613.62",
    ),
    (
        "Block height 715680",
        "0000000000000000000769594a98bd5a813e8554c5eded0ddb994a0ff2546fcf",
        0x170b98ab,
        "24272331996979.97",
    ),
    (
        "Block height 717696",
        "0000000000000000000335dd327bde445d83f1ce40af2736a7c279045b9a55bf",
        0x170b8c8b,
        "24371874614345.62",
    ),
    (
        "Block height 719712",
        "0000000000000000000a67a239660d76031c0e550b1c301897ad02fc857a813a",
        0x170a9080,
        "26643185256535.46",
    ),
    (
        "Block height 721728",
        "0000000000000000000a157e538ac130f4e6c7b6822fb74825c66292ccf65f2c",
        0x170a8bb4,
        "26690525287405.5",
    ),
    (
        "Block height 723744",
        "000000000000000000063060258d0645ed324ff5feab45fbeb7dfe062882e05d",
        0x170a1078,
        "27967152532434.23",
    ),
    (
        "Block height 725760",
        "0000000000000000000907143bf272e051dd1596a343d445fdc39e159be80030",
        0x170a3773,
        "27550332084343.84",
    ),
    (
        "Block height 727776",
        "000000000000000000000515b4b0a46b041dfe655e7a7d9104cc3f99d8e467ad",
        0x170a40c0,
        "27452707696466.39",
    ),
    (
        "Block height 729792",
        "00000000000000000002dde19c2ee636fd7fe1e9a5f21b935af3d8733b88a6af",
        0x1709d897,
        "28587155782195.14",
    ),
    (
        "Block height 731808",
        "00000000000000000001762e25695d69428a85a278aae4743814879006a902a8",
        0x1709f8d9,
        "28225928151211.1",
    ),
    (
        "Block height 733824",
        "000000000000000000002c5b72a7137d55c4c4c65d862d665157b20e7915f4b5",
        0x17097275,
        "29794407589312.08",
    ),
    (
        "Block height 735840",
        "0000000000000000000153990bd58860af764cc7a49c8755416e12d4b6df6233",
        0x170901ba,
        "31251101365711.12",
    ),
    (
        "Block height 737856",
        "0000000000000000000230d9bb1db81e56916b0c2c7363231e75b82b24714482",
        0x17096a20,
        "29897409688833.63",
    ),
    (
        "Block height 739872",
        "00000000000000000007ca944a92c96b6541faf8115b740fdaecabf980d43bb9",
        0x17094b6a,
        "30283293547736.68",
    ),
    (
        "Block height 741888",
        "0000000000000000000745d7eb5b20176409264bf9ea399d977e24fa3d3186f5",
        0x170984cc,
        "29570168636357.99",
    ),
    (
        "Block height 743904",
        "00000000000000000001afca1c73f265e6561f55c13237be2d1dddd9a3640c4e",
        0x1709a7af,
        "29152798808271.88",
    ),
    (
        "Block height 745920",
        "0000000000000000000a15ae7048f8adaca3ffdbdb6857a3f4610752a61f441a",
        0x170a2a04,
        "27692567959233.59",
    ),
    (
        "Block height 747936",
        "00000000000000000002cdaaec7982b641c65d12ceb25fd894ba908e55ed6e6c",
        0x1709fd7e,
        "28174668481289.41",
    ),
    (
        "Block height 749952",
        "00000000000000000007edd9a88903ad4f948bf3def71a520635ec769065429a",
        0x1709ed88,
        "28351606743493.77",
    ),
    (
        "Block height 751968",
        "00000000000000000002a97e2ca050b5cdf26b923ebec48081ef45eb721bfbb6",
        0x17091620,
        "30977051760460.06",
    ),
    (
        "Block height 753984",
        "00000000000000000005a9dc6d0a9cb3177fcbedf4d89516c357a9a00d661e6b",
        0x1708c894,
        "32045359565303.14",
    ),
    (
        "Block height 756000",
        "000000000000000000073cdaa0c1e5f91707f7b3217a4b3265d2e783f2fa83db",
        0x1708f9ae,
        "31360548173144.85",
    ),
    (
        "Block height 758016",
        "00000000000000000005e5ddf901baa6810c88926d55f21d0fee8969cf3447c1",
        0x1707e772,
        "35610794164371.65",
    ),
    (
        "Block height 760032",
        "00000000000000000003faffa0adf6b3767420ba37378f051e31ec149ba36eff",
        0x1707a429,
        "36835682546787.98",
    ),
    (
        "Block height 762048",
        "00000000000000000006b8491f82a5bf6454caa1579fc830ead1fe750e054f1a",
        0x1707a812,
        "36762198818467.21",
    ),
    (
        "Block height 764064",
        "00000000000000000006da48b920343944908861fa05b28824922d9e60aaa94d",
        0x17079e15,
        "36950494067222.41",
    ),
    (
        "Block height 766080",
        "00000000000000000005e69a1a07c24511f2808bdf83895d91e0dacc9265872f",
        0x17083830,
        "34244331613176.18",
    ),
    (
        "Block height 768096",
        "00000000000000000004e0784e32fc507c19cffef55341b72e436a3ce084e866",
        0x1707f590,
        "35364065900457.12",
    ),
    (
        "Block height 770112",
        "0000000000000000000319ded5a8540f0c9e216427488927662ebee95c6a8d81",
        0x1708417e,
        "34093570325203.84",
    ),
    (
        "Block height 772128",
        "0000000000000000000006eae799f36a8311faaf30484bbd2e4063d212213a59",
        0x17077ce2,
        "37590453655497.09",
    ),
    (
        "Block height 774144",
        "00000000000000000001a77e727d194f51e452b237cb6e790922d506c99ce943",
        0x17072720,
        "39350942467772.63",
    ),
    (
        "Block height 776160",
        "000000000000000000037e587e69ca72844a7f67939b67c4c040ea041403afba",
        0x17073039,
        "39156400059293.19",
    ),
    (
        "Block height 778176",
        "0000000000000000000151e32f3acdf30bf7257c3a5d34ba651d086af6b30db2",
        0x170689a3,
        "43053844193928.45",
    ),
    (
        "Block height 780192",
        "00000000000000000004508cac63bb138580e544c57f8b01554fccb07933154d",
        0x17067681,
        "43551722213590.37",
    ),
    (
        "Block height 782208",
        "0000000000000000000076acfce63e6c87be94688d78ed17ed527db0ff8e56c0",
        0x1706023e,
        "46843400286276.55",
    ),
    (
        "Block height 784224",
        "00000000000000000001385f5d2702f5053084a957dd221074114a0b64ea86eb",
        0x1705e0b2,
        "47887764338536.25",
    ),
    (
        "Block height 786240",
        "00000000000000000004347b2042440453c912abdab88bdeafaeb105ac076f91",
        0x1705c739,
        "48712405953118.43",
    ),
    (
        "Block height 788256",
        "0000000000000000000329cacdc041ababd5015748006df4147ff2cc692905af",
        0x1705dd01,
        "48005534313578.78",
    ),
    (
        "Block height 790272",
        "0000000000000000000550e3a138f84f8425d4a7921a336220049987cbfd1f76",
        0x1705ae3a,
        "49549703178592.68",
    ),
    (
        "Block height 792288",
        "000000000000000000016217334cf59ad38fbe7b3804f4c091169dd07ddb8f5e",
        0x17057e69,
        "51234338863442.89",
    ),
    (
        "Block height 794304",
        "00000000000000000002a68398066b170041e30156d28c504bb401ef5b90b0a3",
        0x1705606d,
        "52350439455487.47",
    ),
    (
        "Block height 796320",
        "00000000000000000004a7fc86b4d526ad0453a4a39d73327530ee54c678cbfe",
        0x17058ebe,
        "50646206431058.09",
    ),
];
```

</details>

**Review by softsimon — CHANGES_REQUESTED** [review]
Please rebase.

The Bitcoin Core emulated way with response as a "string" is acceptable.

**Comment by junderw** [comment]
> Bitcoin Core emulated

Just to be clear, there is no way to emulate Bitcoin Core without compiling using the same C++ compiler as the current version of Core.

The only way we can match Bitcoin Core is to make an RPC call to Bitcoin Core and get the raw JSON response data before Rust parses it, copy that as a string into some cache, and return that string to the client calling electrs.

Also, Bitcoin Core could decide to use a new C++ edition and compiler tomorrow and the precision can suddenly change, so we need to make sure that our production servers always use the same exact version of Bitcoin Core and exact compiler (or we use the distributed compiled binaries).

And even then, mempool's difficulty precision might differ from some mining pool that decides they want to compile their own Bitcoin Core with a custom compiler or something.

---

tl;dr Yes, I can get the exact precision from Bitcoin Core. Yes I can cache it somewhere so that we're not calling RPC every block request... but no, even with that, we can not guarantee that the precision of the float will always be exactly the same as every other block explorer and every other mining pool.

The difficulty float is not meant to be a consensus critical piece of data, it's just "taking the consensus thing and making it human readable as "how many times the genesis block difficulty" for the plebs."... anyone who cares about the precision should be reminded that in float notation: `0.1 + 0.2 == 0.30000000000000004` is `true`.

I disagree that it is worthwhile to pursue this.

**Comment by junderw** [comment]
Not to mention: All of our competitors are all over the place. Clearly if anyone is relying on the Difficulty being 15 decimals vs. 14 decimals........ they better be using Bitcoin Core with a fixed compiler....

<details>
 <summary>Click here to see other block explorers with screenshots</summary>

bitcoin-cli / RPC = 8 decimal places. (Also, 15 sig figs which breaks my assumptions of 16 sig figs, since 90% of the other difficulties are 16 sig figs)
Screenshot_2023-07-29_13-11-51

Blockcypher = Doesn't show difficulty at all.
Screenshot_2023-07-29_13-06-50

blockchain dot com = Shows 2 decimal places
Screenshot_2023-07-29_13-07-14

blockchair = Rounds up at 0.5
Screenshot_2023-07-29_13-09-46

blockstream info = Rounds down (uses electrs, so same behavior as we have currently)
Screenshot_2023-07-29_13-13-50

btc dot com = .....??????????? what is this?????
Screenshot_2023-07-29_13-22-29

bitaps dot com = Rounds down
Screenshot_2023-07-29_13-25-52

</details>

**Comment by softsimon** [comment]
> I disagree that it is worthwhile to pursue this.

So your point is we should not pursue being close to Core with some hacks .. but rather use the more accurate simple calculation and return a Number in the API.

I concur.

**Comment by junderw** [comment]
> I concur.

Ok, in that case, this PR is ready for merge.

**Review by softsimon — APPROVED** [review]
tested ACK @ [02aedf5bf41]

**Comment by wiz** [comment]
We can't merge this yet because it will cause the difficulty adjustments to be wrong:

Screenshot 2023-07-31 at 16 51 59
